networks:
  test_gc_network:

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_gc_php_fpm_container
    expose:
      - 9000
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "php", "--version" ]
      interval: 3s
      retries: 5
      timeout: 5s
    volumes:
      - ./:/var/www/html
    networks:
      - test_gc_network

  nginx:
    image: nginx:stable-alpine
    container_name: test_gc_nginx_container
    restart: unless-stopped
    ports:
      - "8002:80"
    depends_on:
      php-fpm:
        condition: service_healthy
    volumes:
      - ./:/var/www/html
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test_gc_network
